### ISSUE TITLE
Waypoint import is broken

### ISSUE THREAD

**Issue by mbethke** [open-wanderer/wanderer#464]
When importing a trail with a few hundred waypoints I got "error saving trail" in the GUI.
PocketBase logs show an error inserting waypoints:
```
{
  "data": {
    "id": "Value must be unique"
  },
  "raw": "id: Value must be unique."
}
```
I'm not sure how IDs are assigned— typically they'd be automatically assigned by the DB engine but I don't think that can be the case here?
Checking the table reveals a whole bunch of already imported waypoints. I think they should have a forgein key linking them to the trail and/or be inserted in a single transaction so waypoint leftovers not connected to a trail can't happen.

**Comment by Flomp** [comment]
I now save the trail first and the waypoints afterwards. So now even when a waypoint upload fails all previous waypoints (and the trail) are created in the database. Please report back if this fixes the issue, with the next patch.

**Comment by Flomp** [comment]
Hopefully fixed with v0.18.2

**Comment by mbethke** [comment]
Unfortunately it's still broken, with a fairly nondescript error message.

<img width="508" height="298" alt="Image" src="https://github.com/user-attachments/assets/1afccfcb-f717-4b6e-9892-c70ad2133c33" />

Only PocketBase says "multipart: message too large" now.
The track I tried to import is this one: https://ridewithgps.com/routes/42089799

**Comment by mbethke** [comment]
The error message seems to come directly from Go's [`multipart` package](https://golang.google.cn/pkg/mime/multipart/). PB defines [a fixed memory limit of 32 MB](https://github.com/pocketbase/pocketbase/blob/master/tools/router/event.go#L325), which *should* be plenty for my track that's only 2 MB of GPX. No idea what's going on there.

**Comment by Flomp** [comment]
I don't have a ridewithgps account. Would you be able to attach the GPX/FIT file here (you can rename it to .txt)?

**Comment by mbethke** [comment]
Sorry, didn't realise it's not downloadable without a login! Here comes.

[Kenya_Bike_Odyssey_Bikepacking_Route-v2025-08.txt](https://github.com/user-attachments/files/22453309/Kenya_Bike_Odyssey_Bikepacking_Route-v2025-08.txt)

**Comment by mbethke** [comment]
Update for 0.18.3: the import itself seems fine initially and everything shows on the map including all waypoints. I still get "Error saving trail" when I try to save it, with PocketDB responding to a POST to `/api/collections/trails/records?expand=category%2Cwaypoints_via_trail%2Csummit_logs_via_trail%2Ctrail_share_via_trail%2Ctags` with "multipart: message too large".

**Comment by cbram** [comment]
I am running into the same issue. My GPX File has about 9500 GPS positions and 150 waypoints. Import seems to work fine. The track looks good on the maps, all waypoints are listed. But when I try to save I get an error message in the WebUI like "Error saving route". When I use the very same GPX file where I removed all waypoints import and saving works. Even a reduced number of Waypoints (1 instead of 150) works.

**Comment by mbethke** [comment]
@Flomp does this still need any more info? I'd be happy to debug further, although I'm not sure where to start. This "multipart: message too large" should not happen for messages way bigger than the track (64 MB at least, IIRC) and I can't find anything where the post size could be inflated this much.

**Comment by slothful-vassal** [comment]
hopefully fixed with #969
